codecov:
  token: 80fb5b55-d176-4a71-a6fb-4bdada29ad0d

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
